"""
Problem: Each new term in the fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2 , the first 10 terms will be 1,2,3,5,8,13,21,34,55,89
By considering the terms in the fibonacci sequence whose value doesnot exceed 4 million, find the sum of even valued number

"""

maximum=4000000


def fibonacci_sum(maximum):
    first_element = 1
    second_element = 2
    even_sum = 0  

    while first_element <= maximum:
        if first_element % 2 == 0:
            even_sum += first_element  
        
        next_element = first_element + second_element
        first_element = second_element
        second_element = next_element

    print(even_sum)
fibonacci_sum(maximum)


